steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - engine/worker/Dockerfile
      - -t
      - ${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_IMAGE_NAME}:$COMMIT_SHA
      - engine

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_IMAGE_NAME}:$COMMIT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image
      - ${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_IMAGE_NAME}:$COMMIT_SHA
      - --region
      - ${_SERVICE_REGION}
      - --platform
      - managed
      - --no-allow-unauthenticated
      - --set-env-vars
      - ENGINE_ENABLE_SCHEDULER=true

images:
  - ${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_IMAGE_NAME}:$COMMIT_SHA

substitutions:
  _AR_REGION: us-east4
  _AR_REPOSITORY: cloud-run-source-deploy
  _IMAGE_NAME: wtd-worker-control
  _SERVICE_NAME: cogotchi-worker
  _SERVICE_REGION: us-east4
