"""BenchmarkPackBuilder — auto-generate benchmark packs from predictive events.

Takes a list of ExtremeEvent objects (filtered to is_predictive=True), selects
the best reference + holdout cases, verifies data availability in the offline
cache, and writes a JSON benchmark pack compatible with
``engine/research/pattern_search/benchmark_packs/``.

Pack selection strategy:
  reference = event with highest outcome_72h (best real-world case)
  holdout   = remaining events sorted by outcome_72h desc, top N
"""
from __future__ import annotations

import json
import uuid
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

from research.event_tracker.models import ExtremeEvent

BENCHMARK_PACK_DIR = (
    Path(__file__).resolve().parents[2] / "research" / "pattern_search" / "benchmark_packs"
)

# Default expected phase path for funding-flip-reversal-v1
FFR_EXPECTED_PATH = [
    "SHORT_OVERHEAT",
    "COMPRESSION",
    "FLIP_SIGNAL",
    "ENTRY_ZONE",
    "SQUEEZE",
]


class BenchmarkPackBuilder:
    """Build benchmark pack JSON from a list of predictive ExtremeEvents.

    Usage::

        builder = BenchmarkPackBuilder()
        pack = builder.build_from_events(
            pattern_slug="funding-flip-reversal-v1",
            events=predictive_events,
        )
        builder.save_pack(pack, "funding-flip-reversal-v1__auto-apr26.json")
    """

    def __init__(
        self,
        pack_dir: Path = BENCHMARK_PACK_DIR,
        lookback_days_before: int = 14,    # days before event for start_at
        lookahead_days_after: int = 14,    # days after event for end_at
    ) -> None:
        self.pack_dir = pack_dir
        self.lookback_days_before = lookback_days_before
        self.lookahead_days_after = lookahead_days_after

    def build_from_events(
        self,
        pattern_slug: str,
        events: list[ExtremeEvent],
        *,
        n_reference: int = 1,
        n_holdout: int = 3,
        expected_phase_path: list[str] | None = None,
        pack_id_suffix: str | None = None,
    ) -> dict[str, Any]:
        """Build a benchmark pack dict from the given predictive events.

        Args:
            pattern_slug: Pattern slug (e.g. "funding-flip-reversal-v1").
            events: List of ExtremeEvent, should all have outcome_72h set.
            n_reference: Number of reference cases to include. Default 1.
            n_holdout: Number of holdout cases. Default 3.
            expected_phase_path: Phase sequence for the pattern. If None,
                defaults to FFR_EXPECTED_PATH.
            pack_id_suffix: Suffix for the benchmark_pack_id. Auto-generated
                from current date if None.

        Returns:
            Dict matching the benchmark pack JSON schema.

        Raises:
            ValueError: If fewer than (n_reference + 1) events are available
                or no events have cache data.
        """
        # Filter to events that have cache data
        available = [ev for ev in events if self._has_cache_data(ev)]
        if len(available) < n_reference:
            raise ValueError(
                f"Need ≥{n_reference} events with cache data, got {len(available)}"
            )

        # Sort by outcome_72h desc — best outcomes first
        available.sort(key=lambda e: e.outcome_72h or 0.0, reverse=True)

        references = available[:n_reference]
        holdouts = available[n_reference: n_reference + n_holdout]

        if expected_phase_path is None:
            expected_phase_path = FFR_EXPECTED_PATH

        suffix = pack_id_suffix or datetime.now(tz=timezone.utc).strftime("auto-%b%y").lower()
        pack_id = f"{pattern_slug}__{suffix}"

        cases = []
        for ev in references:
            cases.append(self._event_to_case(ev, "reference", expected_phase_path))
        for ev in holdouts:
            cases.append(self._event_to_case(ev, "holdout", expected_phase_path))

        return {
            "benchmark_pack_id": pack_id,
            "pattern_slug": pattern_slug,
            "candidate_timeframes": ["1h"],
            "cases": cases,
            "created_at": datetime.now(tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%S+00:00"),
            "_generated_by": "BenchmarkPackBuilder (W-0099)",
        }

    def _event_to_case(
        self,
        ev: ExtremeEvent,
        role: str,
        expected_phase_path: list[str],
    ) -> dict[str, Any]:
        """Convert one ExtremeEvent to a benchmark case dict."""
        detected = ev.detected_at or datetime.now(tz=timezone.utc)
        if detected.tzinfo is None:
            detected = detected.replace(tzinfo=timezone.utc)

        start_at = detected - timedelta(days=self.lookback_days_before)
        end_at = detected + timedelta(days=self.lookahead_days_after)

        notes = [
            f"Auto-generated by BenchmarkPackBuilder (W-0099).",
            f"Event: {ev.event_type}, trigger={ev.trigger_value:.6f}, detected={detected.isoformat()}.",
        ]
        if ev.outcome_72h is not None:
            notes.append(f"72h outcome: {ev.outcome_72h:+.1%}")
        if ev.notes:
            notes.append(ev.notes)

        return {
            "symbol": ev.symbol,
            "timeframe": ev.timeframe,
            "start_at": start_at.strftime("%Y-%m-%dT%H:%M:%S+00:00"),
            "end_at": end_at.strftime("%Y-%m-%dT%H:%M:%S+00:00"),
            "expected_phase_path": expected_phase_path,
            "role": role,
            "notes": notes,
            "case_id": ev.event_id,
        }

    def _has_cache_data(self, ev: ExtremeEvent) -> bool:
        """Check if the symbol has both 1h klines and perp data in the cache."""
        from data_cache.loader import cache_path  # local import
        klines_path = cache_path(ev.symbol, "1h")
        # perp path convention: SYMBOLUSDT_perp.csv
        from pathlib import Path as _Path
        cache_dir = klines_path.parent
        perp_path = cache_dir / f"{ev.symbol}_perp.csv"
        return klines_path.exists() and perp_path.exists()

    def save_pack(self, pack: dict[str, Any], filename: str) -> Path:
        """Save a benchmark pack dict to the benchmark_packs directory.

        Returns the path of the saved file.
        """
        self.pack_dir.mkdir(parents=True, exist_ok=True)
        out_path = self.pack_dir / filename
        with out_path.open("w") as f:
            json.dump(pack, f, indent=4)
        return out_path

    def build_and_save(
        self,
        pattern_slug: str,
        events: list[ExtremeEvent],
        filename: str | None = None,
        **kwargs,
    ) -> Path:
        """Build and save in one call. Returns the saved file path."""
        pack = self.build_from_events(pattern_slug, events, **kwargs)
        if filename is None:
            suffix = pack.get("benchmark_pack_id", pattern_slug).split("__")[-1]
            filename = f"{pattern_slug}__{suffix}.json"
        return self.save_pack(pack, filename)
